#!/bin/sh

set -e

dbcnf_mysqluser='playsms/mysql-username'
dbcnf_mysqlpass='playsms/mysql-password'

# start up debconf and tell it the protocol version
. /usr/share/debconf/confmodule
db_version 2.0

# tell debconf what template questions to ask
db_input high $dbcnf_mysqluser || true
db_input high $dbcnf_mysqlpass || true

# tell debconf to ask the questions
db_go || true

