#!/bin/sh

set -e

package=playsms

# start up debconf
. /usr/share/debconf/confmodule

# start up dbconfig-common
# (uses debconf to config the database)
#
if [ -f /usr/share/dbconfig-common/dpkg/config.mysql ]; then
	. /usr/share/dbconfig-common/dpkg/config.mysql 

    # first version that started using dbconfig-common
	dbc_first_version="0.8.3"

	#dbc_load_include="sh:/etc/$package/db.conf"

	dbc_go $package $@
fi

